allowBuilds:
  '@vscode/vsce-sign': false
  keytar: false
minimumReleaseAgeExclude:
  - brace-expansion@5.0.9

overrides:
  "brace-expansion@5": 5.0.9

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm64
    - x64
