/* This generic fixture models the file generated by React Native Storybook. */

import { start } from "@storybook/react-native";
import "@storybook/addon-ondevice-actions/register";

import preview from "./preview";

export const view = start({
  annotations: [preview],
  storyEntries: [],
});
