/**
 * Generate `src/generated/output-contract.d.ts` from `docs/output-schema.json`.
 *
 * Output is committed to git. A `check:codegen` script regenerates to a temp
 * path and diffs against the committed file so CI catches forgotten regens.
 *
 * Run: `pnpm --filter fallow-vscode codegen:types`
 *      `pnpm --filter fallow-vscode check:codegen`
 */
import { compile } from "json-schema-to-typescript";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const EXTENSION_ROOT = resolve(SCRIPT_DIR, "..");
const REPO_ROOT = resolve(EXTENSION_ROOT, "..", "..");
const SCHEMA_PATH = resolve(REPO_ROOT, "docs", "output-schema.json");
const OUT_PATH = resolve(
  EXTENSION_ROOT,
  "src",
  "generated",
  "output-contract.d.ts",
);

const BANNER = `/**
 * AUTOGENERATED FILE. DO NOT EDIT.
 *
 * Generated from \`docs/output-schema.json\` by
 * \`editors/vscode/scripts/codegen-types.mjs\`.
 *
 * To change a shape:
 *   1. Edit the Rust struct in \`crates/types/src/results.rs\` (or the
 *      duplicates crate at \`crates/core/src/duplicates/types.rs\`). The Rust
 *      side is the runtime source of truth for the JSON output.
 *   2. Update \`docs/output-schema.json\` to match. The schema is
 *      hand-maintained against the Rust structs; the drift-guard test in
 *      \`crates/cli/src/report/json.rs\` enforces only a subset of the
 *      contract (the \`HealthFindingAction\` enum). Field-level drift between
 *      Rust and the schema is currently caught by code review.
 *   3. Run \`pnpm --filter fallow-vscode codegen:types\` from anywhere.
 *   4. Commit the regenerated file alongside the schema edit.
 *
 * CI runs \`pnpm --filter fallow-vscode check:codegen\` which fails when
 * the committed file disagrees with what regen would produce.
 */
/* eslint-disable */
`;

const OPTIONS = {
  // Default for objects whose schema does not declare additionalProperties.
  // The schema is intentionally permissive at validation time (forward-compat
  // for JSON validators on older fallow versions), but for the TypeScript
  // contract we want closed shapes: missing-field reads should be a compile
  // error, not silent `unknown`.
  additionalProperties: false,
  bannerComment: BANNER,
  // Skip prettier formatting. jstt's raw output is stable across invocations,
  // which keeps the drift-check diff trivial. The committed file is read-only
  // for humans anyway.
  format: false,
  // Use `unknown` rather than `any` for the rare cases the schema admits it.
  unknownAny: true,
  // Include all named definitions, including helpers like SchemaVersion that
  // are referenced via $ref but not directly under the root oneOf.
  unreachableDefinitions: true,
  // Use the file path itself for ref resolution.
  cwd: REPO_ROOT,
};

/**
 * Strip `title` from the schema root AND every definition before generation.
 * jstt prefers `title` over the definition key (or the explicit name argument
 * passed to `compile`) when naming generated types: documentary titles like
 * "fallow dead-code --format json" otherwise become mangled names like
 * `FallowDeadCodeFormatJson` (plus a duplicate `CheckOutput`), and the root
 * title "Fallow JSON Output Schemas" otherwise becomes `FallowJSONOutputSchemas`
 * regardless of the second argument to `compile`.
 *
 * We keep `description` (used as JSDoc) and only drop `title` (TS naming).
 */
function stripTitles(schema) {
  if ("title" in schema) {
    delete schema.title;
  }
  if (schema.definitions) {
    for (const def of Object.values(schema.definitions)) {
      if (def && typeof def === "object" && "title" in def) {
        delete def.title;
      }
    }
  }
  return schema;
}

/**
 * Walk the schema and remove sibling keys next to `$ref`. JSON Schema Draft 07
 * specifies that `$ref` siblings are ignored at validation time, but jstt
 * treats `{ "$ref": "...", "description": "..." }` as an inline schema and
 * generates a duplicate type rather than emitting a plain alias. Stripping
 * the `description` (and any other sibling) at codegen time keeps generated
 * names canonical without losing the documentation in the source schema.
 */
function flattenRefSiblings(node) {
  if (!node || typeof node !== "object") return node;
  if (Array.isArray(node)) {
    for (const item of node) flattenRefSiblings(item);
    return node;
  }
  if (typeof node.$ref === "string") {
    for (const key of Object.keys(node)) {
      if (key !== "$ref") delete node[key];
    }
    return node;
  }
  for (const value of Object.values(node)) flattenRefSiblings(value);
  return node;
}

async function generate() {
  const raw = await readFile(SCHEMA_PATH, "utf8");
  const parsed = JSON.parse(raw);
  stripTitles(parsed);
  flattenRefSiblings(parsed);
  // With the root title stripped, jstt uses the second arg as the name of the
  // top-level union type.
  return compile(parsed, "FallowJsonOutput", OPTIONS);
}

async function write(contents) {
  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, contents, "utf8");
}

async function check() {
  const generated = await generate();
  const committed = await readFile(OUT_PATH, "utf8").catch(() => "");
  if (committed === generated) {
    return 0;
  }
  process.stderr.write(
    "\x1b[31mcheck:codegen FAILED\x1b[0m: " +
      "`src/generated/output-contract.d.ts` is out of date with " +
      "`docs/output-schema.json`.\n" +
      "Run `pnpm --filter fallow-vscode codegen:types` and commit the result.\n",
  );
  return 1;
}

const mode = process.argv[2];
if (mode === "--check") {
  const code = await check();
  process.exit(code);
} else {
  const contents = await generate();
  await write(contents);
  process.stdout.write(`Wrote ${OUT_PATH}\n`);
}
