/* do not change this file, it is auto generated by storybook. */

import { start, updateView } from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: './src',
    files: '**/*.stories.?(ts|tsx|js|jsx)',
    // @ts-ignore
    req: require.context('../src', true, /\.stories\.(ts|tsx|js|jsx)$/),
  },
];

const annotations = [
  require('./preview'),
  require('@storybook/addon-ondevice-actions/preview'),
];

// @ts-ignore
global.STORIES = normalizedStories;

// @ts-ignore
if (!global.view) {
  // @ts-ignore
  global.view = start({ annotations, storyEntries: normalizedStories });
} else {
  // @ts-ignore
  updateView(global.view, annotations, normalizedStories);
}

// @ts-ignore
export const view = global.view;
